"use client"

import Navbar from "src/components/(Navbar)/Navbar"
import Hero from "src/components/Hero"
import Benefits from "src/components/(Benefits)/Benefits"
import OurClasses from "src/components/(OurClasses)/OurClasses"
import ContactUs from "src/components/ContactUs"
import Footer from "src/components/Footer"
import { useEffect, useState } from "react"
import { SelectedPage } from "src/shared/types"

export const metadata = {
  title: "Home | EvoGym | DinWebDev",
  description: "Generated by create next app",
}

export default function Home() {
  const [selectedPage, setSelectedPage] = useState<SelectedPage>(
    SelectedPage.Home
  )

  const [isTopOfPage, setIsTopOfPage] = useState<boolean>(true)

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY === 0) {
        setIsTopOfPage(true)
        setSelectedPage(SelectedPage.Home)
      }
      if (window.scrollY !== 0) setIsTopOfPage(false)
    }
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  return (
    <div className="app bg-gray-20">
      <Navbar
        isTopOfPage={isTopOfPage}
        selectedPage={selectedPage}
        setSelectedPage={setSelectedPage}
      />
      <Hero setSelectedPage={setSelectedPage} />
      <Benefits setSelectedPage={setSelectedPage} />
      <OurClasses setSelectedPage={setSelectedPage} />
      <ContactUs setSelectedPage={setSelectedPage} />
      <Footer />
    </div>
  )
}
